[package]
name = "artigen"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.1"
image = "0.24.5"
imageproc = { version = "0.23.0", features = ["display-window"] }
num-complex = "0.4.2"
