[package]
name = "artigen"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.1"
image = "0.24.5"
imageproc = "0.23.0"
num-complex = "0.4.2"
rand = "0.8.5"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
